### ISSUE TITLE
does not check for '../' in filename

### ISSUE THREAD

**Issue by appelflap** [hamidsamak/pheditor#1]
This way all readable system files could be shown in the editor.
Would be good to 'jail' it to the current __DIR__.

Use F12 to edit the 'a href' of a listed file: `data-file="../somefile.txt"`
Click the row. And view it. 

The PHP also does not check the file extension of the requested file. So even if you limited the files to *.txt, you will still be able to edit/view *.conf files and others.

**Comment by hamidsamak** [comment]
Correct,
Bug fixed.

Thanks for report
