### ISSUE TITLE
[question] No pass

### ISSUE THREAD

**Issue by nagualcode** [hamidsamak/pheditor#10]
Hello, thank you for this great project.
How can I make it passwordless ?
I have I use case where I dont need/want a login prompt.

For the record, I have noticed that if the server has 2 pheditors, separeted dirs and phpfiles, when you login in one of them, you will be able to log the other, even if the password is different.
Thank you!

**Comment by hamidsamak** [comment]
Hi @nagualcode,

I have added new feature to use Pheditor without login or password.
You just need to edit the file and delete password hash from `PASSWORD` constant.
`define('PASSWORD', '');`

The bug for multiple Pheditors on the same domain name will be fixed soon.

**Comment by hamidsamak** [comment]
Bug fixed for using script on the same domain name and different paths.
