### ISSUE TITLE
"Invalid file pattern" when creating subdirectories or files

### ISSUE THREAD

**Issue by Linkinverse** [hamidsamak/pheditor#17]
Whenever i try to create a textfile into a sudirectory i receive the following error message: "Invalid file pattern".

I tried both Firefox and Chrome, with PHP 7.3 on XAMPP and various web hosting, always with the same result.

**Comment by Linkinverse** [comment]
UPDATE: i verified and i confirm **this was working until commit: Sep 7, 2019**

**Comment by hamidsamak** [comment]
There is a new option in the configuration as `PATTERN_FILES` which has a list of allowed file extensions for view or create. If you want to skip this option empty the constant value.

**Comment by Linkinverse** [comment]
I can assure you there is a big in the last versions after 7th September:
deep subfolders and nested files **(any extension)** cannot be created.

Please double-check, the bug can be replicated on any webserver and with all browsers.

**Comment by hamidsamak** [comment]
It seems ok. Please check the owner and permission of your file.
You can check with 0777 permission.
