### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Linkinverse** [hamidsamak/pheditor#18]
Saving any sensitive information can be an issue because the password login can be bypassed by **accessing the files on disk directly** (i.e. the sysadmin has access to the disk!).

I know this could be over your idea of small utility but still the impelmentation of this optional feature is **literally 1 line of code** so please consider adding it!

**Hoping to help, here is an example of superquick implementation (AES encryption):**
`base64_encode(mcrypt_encrypt(MCRYPT_RIJNDAEL_256, md5($key), $textstring, MCRYPT_MODE_CBC, md5(md5($key))));`
Note: this is really fast.

(the hash of the login password itself could be used as key for coding/decoding for maximum security to avoid using a static one)

I hope you will consider my suggestion, you did an awesome job btw! Thank you ❤

**Comment by hamidsamak** [comment]
If someone has access to disk directly it means he can do anything to the files. So he doesn't need to know your Pheditor password. If you mean to encrypt/decrypt files contents after edits I have to say that this project is only a file editor for web-developers who want to edit files quickly on the server and not to use FTP or other web panels. It doesn't really make sense to encrypt a PHP file content that is hosted on web-server.

The login password is not stored as a string, if you check the source code you will see it is stored as SHA256 hash and it is one-way encryption.

**Comment by Linkinverse** [comment]
Yes, I mean encrypt files contents using the SHA256 itself as the encryption password.
This way even with direct access to the disk, nobody could read them. I think it's a neat feature!

You decide. This feature request was based on the fact that your program is currently the best "cloud" **Outliner**.

**Comment by hamidsamak** [comment]
Honestly, I've never seen an IDE before with the ability to encrypt file contents. I'm not going to say that is impossible, just want to say that it isn't necessary for an IDE or code editor in my opinion. There are many other ways to protect files, for example, encrypted disk partitions or hundreds of software for this purpose.
