### ISSUE TITLE
Feature/Error: Add before unload if unsaved

### ISSUE THREAD

**Issue by flynow10** [hamidsamak/pheditor#20]
It would be nice if you could a before unload js function when the file is unsaved and not just when going to a different file. Thanks!

**Comment by hamidsamak** [comment]
As the unsaved file changes work with SHA512 digest and this function uses promises, cannot have this feature because `onbeforeload` event will not wait for promise result.
There are some other ways such as intervals and calculating digest every n seconds but it causes the browser to slow down.
