### ISSUE TITLE
Main Editor does not work on sub-level folders

### ISSUE THREAD

**Issue by Alex-Goaga** [hamidsamak/pheditor#24]
The main file, pheditor.php, does not open to edit the files from any sub-folders. On the root works as described.

More information : 
The pheditor.min.php works correctly on all sub-folders and root location.

I am doing something wrong?
Thank you

EDIT 1 : additional information : 
The bug repros if the setup if one like this : 

./htdocs
├── admin
│   └── meow.php <- CAN'T be edited 
├── css
│   └── main.css <- CAN'T be edited
├── index.html <- can be edited 
└── some-file.php <- can be edited 
└── pheditor.php

The bug does not "fully" reproduce if the setup is one like this : 
./htdocs
├── admin
│   └── meow1.php <- this can be edited 
│   └── meow2.php <- this can be edited 
│   ├──  another_folder_name
      (// pheditor.php has the path now of : htdocs / admin / another_folder_name)
│                    |└── pheditor.php  -> changed to define('MAIN_DIR', dirname(__DIR__, 2));
├── another_folder
│   └── meow4.php <- CAN'T be edited
├── css
│   └── main.css <- CAN'T be edited
├── index.html <- this can be edited root
└── some-file.php <- this can be edited root

Keep up the good work,
Alex

**Comment by hamidsamak** [comment]
Hi @Alex-Goaga,

Can you check the permission and owners of the files?
Pheditor is only able to edit the files and directories inside defined MAIN_DIR.

**Comment by shayanariayee** [comment]
i found a trick!!!!!
simply in line 1031 of pheditor.php change from "if (file.length > 0) {"  to  ======> "if (file.length > -1) {"  then it opens all files even in sub folders...
thanks to mr samak..

**Comment by bonnebulle** [comment]
Hello
Here, I dont show any... files or folders
![image](https://github.com/user-attachments/assets/b4904d7a-5d90-4789-999e-52868b997fb9)
Maybe I need a full install (composer) ?
I have no console warning errors !
PHP 8.x
Thanks amazing light project
V.
