### ISSUE TITLE
The "History" changes features does not work in pheditor.min.php

### ISSUE THREAD

**Issue by Alex-Goaga** [hamidsamak/pheditor#26]
When you edit a file , as the code describes, a history file is created.

On the main pheditor.php, works as described:
-> a folder is created
-> corespondent file is created

But in the pheditor.min.php, the code does not do anything, not even the newfolder.

**Comment by hamidsamak** [comment]
The minified version was outdated and now is updated.

File history only keeps the old version of the files before saving new changes.
