### ISSUE TITLE
upload to subfolder always uploads to root folder of pheditor.php

### ISSUE THREAD

**Issue by boschkundendienst** [hamidsamak/pheditor#28]
Hi,

I don't know if I am doing something wrong but I placed `pheditor.php` in a folder on my webspace, let's say folder `entrypoint`. There is a subfolder `img` within this folder. So I want to upload an image into `entrypoint/img/`.

```
entrypoint/
\-pheditor.php

entrypoint/img/
```

I could not achieve this. I select the `img` folder in the left pane. The text right of the `File` Dropdown menu even shows `/entrypoint/img/` and then select `Upload File U`, browse for the image (`image.jpg`) and upload it.

After refreshing the page, the image is now located in `entrypoint/image.jpg` instead of `entrypoint/img/image.jpg`.

```
entrypoint/
\-pheditor.php
\-image.jpg

entrypoint/img/
```

Am I doing something wrong or is this a bug in Pheditor?

Thanks in advance

Bosch

**Comment by hamidsamak** [comment]
Hi @boschkundendienst,

Problem fixed. Thanks for report.

**Comment by boschkundendienst** [comment]
Thank you very much for this awesome fast response!
