### ISSUE TITLE
Bypass Pattern Files

### ISSUE THREAD

**Issue by fjavierc** [hamidsamak/pheditor#29]
Hi;

First of all congratulations on the project, it is a great job.

I am currently testing  pheditor to edit .txt files only and allowing only the following permissions: newfile, editfile, deletefile, renamefile, uploadfile

````
define ('PATTERN_FILES', '/^^ A-Za-z0-9-_.\/> *) .(txt)$/i');
define('PERMISSIONS', 'newfile,editfile,deletefile,renamefile,uploadfile'); 
 `````

I have seen that the "renamefile" permission can be "abused" in order to execute php code on the server since it seems to be missing a check of the pattern files. A use case:

1.  Create a file from the editor (new-file.txt)
2.  The new file is displayed in the "file manager"
3.  Edit the file "new-file.txt" and add, for example:  `<? Php phpinfo.php?>`
4.  Double click on the file "new-file.txt"; opens in a new window and displays " `<? php phpinfo.php?>` as if it were a simple text file
5.  Rename the file "new-file.txt" to "new-file.php"
6.  The renamed file disappears from the file manager
7.  In the tab that was opened in point 4, replace the extension .txt to .php
8.  Refresh the tab and the result of executing the function phpinfo () is displayed;

This can be solved in two ways:

A. Remove 'renamefile' permissions
B. Add a check before executing the rename operation.

In my case, I reuse an existing check in the pheditor code and add it between lines 241 and 242 ( if we see original code ):

**pheditor.php**
````php
[ ...]
case 'rename':
  if (isset($_POST['path']) && file_exists(MAIN_DIR . $_POST['path']) && isset($_POST['name']) && empty($_POST['name']) === false) {

    $path = MAIN_DIR . $_POST['path'];

    //   NEW CODE  HERE
    // Check valid patter files before rename
    if (empty(PATTERN_FILES) === false && !preg_match(PATTERN_FILES, str_replace(basename($path), '', dirname($path)) . DS . $_POST['name']))  {     
      die(json_error('Invalid file pattern: ' )); }**
    
    $new_path = str_replace(basename($path), '', dirname($path)) . DS . $_POST['name'];

    if ($_POST['path'] == '/') {
      echo json_error('Unable to rename main directory');
[...]

````

Well, I know that access to the editor is quite restricted, it has its security measures, etc. but in my case, the editor will be used by several people. I also don't know if there are more pheditor users who are interested to know about this and how to fix it. I would appreciate if you think it is a good solution or if you propose something better (sorry, I'm not a developer)

Thank you very much for your work.

Regards,

**Comment by hamidsamak** [comment]
Problem fixes.
Thanks for your report.
