### ISSUE TITLE
Doesnt save newline on txt file

### ISSUE THREAD

**Issue by wesleycgmartins** [hamidsamak/pheditor#3]
This is an excellent code, and I am trying to implement it for internal use in an educational institution, however I am having a problem, when I click save, it does not identify the line break to save with a new row, it saves the information in same line so that I can save in the line below I have to leave two blank lines so that it recognizes that it is to save with a new line.

Can you help me with that?

Thanks!

**Comment by hamidsamak** [comment]
@wesleycgmartins You're right, problem fixed.
Thanks for reporting.
