### ISSUE TITLE
Feature request: Shortcut for save / ask before delete

### ISSUE THREAD

**Issue by pbov** [hamidsamak/pheditor#5]
For excessive usage I needed a faster way to save an open file. Entry point for macOS was this: https://mycodestock.com/public/snippet/10736

Another issue for me was the Delete-Button which I clicked when I wanted to hit the Save-Button. Maybe a dialog popup would be helpful preventing unwanted deletion :)

**Comment by grosbedos** [comment]
Hi,

Very happy with pheditor, simple and clean.
Same suggestions here, a shorcut to save the file, and a confirmation when you delete a file ;)

Best regards

**Comment by hamidsamak** [comment]
@pbov
@grosbedos
Thanks for your suggestion.
Keyboard shortcuts (creating a new file, save file and switch between the file manager and editor) and confirmation before deleting files added.
The hotkeys are explained in [readme](https://github.com/hamidsamak/pheditor/blob/v2/README.md) file.

Have fun,
Hamid

**Comment by grosbedos** [comment]
Thanks a lot Hamid !
It's working great :D
