### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by davidzoli** [hamidsamak/pheditor#8]
When using the editor, after few saving, I get 403 error for the whole domain on my computer.
Very strange. What is that about? Why this happens?

**Comment by hamidsamak** [comment]
Hello David,
More details will be needed to trace this problem. Such as your web-server, any WAF or blocking service or rewrite rules configured in your web-server.

Can you send the headers of a broken request here?
(You can get the whole results of requests in your browser console).

**Comment by davidzoli** [comment]
Thank you for the answer.
Can that happen because of posting large data? Or posting code to the server? I'm the only one (so far) who faced this problem?
That could be some server thing. However it is a paid hosting service, I don't have much info about the server. I'll try that on a different hosing.
I'll upload the script into a testing folder for you.
The headers look fine. Nothing strange. Code 200 OK, but no data.

**Comment by hamidsamak** [comment]
Yes, It may be because of your web-server configuration, nobody reported such this problem so far.
If you are on Linux you can test it on a pure installation of Apache or NGINX with PHP. (or XAMPP on Windows)
